import { useEffect, useState } from "react";
import { apiRequest } from "../../services/api";

function isOwner(){ try{ const raw=localStorage.getItem("user")??sessionStorage.getItem("user"); const u=raw?JSON.parse(raw):{}; return ["admin","owner"].includes(String(u?.role??"").toLowerCase()); }catch{return false;} }

export default function PaymentDestinationSection(){
 const [allowed]=useState(isOwner); const [method,setMethod]=useState("mpesa"); const [mpesa,setMpesa]=useState(""); const [bank,setBank]=useState(""); const [accountName,setAccountName]=useState(""); const [accountNumber,setAccountNumber]=useState(""); const [branch,setBranch]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{if(!allowed)return; void (async()=>{try{const r:any=await apiRequest("/organization/payment-settings");setMethod(r?.preferred_method??"mpesa");setMpesa(r?.mpesa_number??"");setBank(r?.bank_name??"");setAccountName(r?.bank_account_name??"");setAccountNumber(r?.bank_account_number??"");setBranch(r?.bank_branch??"");}catch{}})()},[allowed]);
 if(!allowed)return null;
 async function save(){setSaving(true);setMessage("");try{await apiRequest("/organization/payment-settings",{method:"PUT",body:JSON.stringify({preferred_method:method,mpesa_number:mpesa,bank_name:bank,bank_account_name:accountName,bank_account_number:accountNumber,bank_branch:branch})});setMessage("Payment destination saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save payment destination.");}finally{setSaving(false);}}
 return <section className="mg-panel"><div className="mg-panel__head"><h2 className="mg-panel__title">Payment destination</h2></div><div className="mg-panel__body"><p className="mg-hint">Only the organization owner or administrator can set where tenant payments are directed. This is the destination configuration that future payment integrations will use.</p><div className="mg-field"><label>Preferred method</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="mpesa">M-Pesa</option><option value="bank">Bank account</option></select></div>{method==="mpesa"?<div className="mg-field"><label>M-Pesa number</label><input value={mpesa} onChange={e=>setMpesa(e.target.value)} placeholder="07xx xxx xxx"/></div>:<><div className="mg-field"><label>Bank name</label><input value={bank} onChange={e=>setBank(e.target.value)}/></div><div className="mg-field"><label>Account name</label><input value={accountName} onChange={e=>setAccountName(e.target.value)}/></div><div className="mg-field"><label>Account number</label><input value={accountNumber} onChange={e=>setAccountNumber(e.target.value)}/></div><div className="mg-field"><label>Branch</label><input value={branch} onChange={e=>setBranch(e.target.value)}/></div></>}<button className="mg-btn mg-btn--primary" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save payment destination"}</button>{message&&<p className="mg-hint" style={{marginTop:".75rem"}}>{message}</p>}</div></section>;
}
