<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // These records were generated by the generic Eloquent observer for
        // OrganizationPaymentSetting. They are implementation-level model
        // events, not organization activity, so remove them from the audit trail.
        DB::table('audit_logs')
            ->where('auditable_type', 'App\\Models\\OrganizationPaymentSetting')
            ->whereIn('description', [
                'OrganizationPaymentSetting created.',
                'OrganizationPaymentSetting updated.',
                'OrganizationPaymentSetting deleted.',
            ])
            ->delete();
    }

    public function down(): void
    {
        // The removed records were invalid generic model events and cannot be
        // reconstructed without duplicating historical implementation noise.
    }
};
