import { FormEvent, useEffect, useState } from "react";
import { AlertCircle, LockKeyhole } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { apiRequest } from "../services/api";

type Invitation={valid:boolean;expires_at:string;employee:{name:string;email:string;role:string};organization:{id:number;name:string;logo_url?:string|null}};
const styles=`
.ai-root{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1.25rem;background:#f6f7f7;color:#24313d}.ai-card{width:min(100%,480px);background:#fff;border:1px solid #e2e7ea;border-radius:1rem;padding:1.5rem;box-shadow:0 18px 50px rgba(27,40,51,.08)}.ai-brand{display:flex;align-items:center;gap:.7rem;margin-bottom:1.5rem}.ai-logo{width:3rem;height:3rem;border-radius:.75rem;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#f0f4f7;color:#315f8a;font-weight:800}.ai-logo img{width:100%;height:100%;object-fit:contain;background:#fff}.ai-eyebrow{margin:0;font-size:.62rem;text-transform:uppercase;letter-spacing:.13em;color:#8c97a0;font-weight:700}.ai-org{margin:.2rem 0 0;font-size:.95rem;font-weight:750}.ai-title{margin:0;font-size:1.55rem;letter-spacing:-.035em}.ai-copy{margin:.5rem 0 1.2rem;color:#7d8891;line-height:1.6;font-size:.82rem}.ai-alert{display:flex;gap:.55rem;align-items:flex-start;padding:.75rem;margin-bottom:1rem;border-radius:.7rem;background:#fbf2f0;color:#82463f;font-size:.78rem}.ai-field{display:grid;gap:.4rem;margin-bottom:1rem}.ai-field label{font-size:.7rem;font-weight:700;color:#68747e}.ai-field input{min-height:2.75rem;padding:.7rem .75rem;border:1px solid #d9e0e4;border-radius:.65rem;font:inherit;outline:none}.ai-field input:focus{border-color:#8ca9bf;box-shadow:0 0 0 3px rgba(49,95,138,.08)}.ai-submit{width:100%;min-height:2.75rem;border:0;border-radius:.7rem;background:#315f8a;color:#fff;font:inherit;font-size:.82rem;font-weight:700;cursor:pointer}.ai-submit:disabled{opacity:.55;cursor:not-allowed}.ai-role{display:inline-block;margin-bottom:1rem;padding:.3rem .55rem;border-radius:999px;background:#f1f4f6;color:#52616e;font-size:.68rem;font-weight:700}`;

function AcceptInvitePage(){
 const [params]=useSearchParams(),navigate=useNavigate(),token=params.get("token")||"";
 const [invitation,setInvitation]=useState<Invitation|null>(null),[loading,setLoading]=useState(true),[password,setPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!token){setError("This invitation link is missing its token.");setLoading(false);return}let cancelled=false;void apiRequest<Invitation>("/team/invitations/"+encodeURIComponent(token)).then(r=>{if(!cancelled)setInvitation(r)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"This invitation is invalid or expired.")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[token]);
 async function submit(event:FormEvent){event.preventDefault();setError("");if(password.length<8){setError("Your password must be at least 8 characters.");return}if(password!==confirmation){setError("The passwords do not match.");return}setSaving(true);try{const r=await apiRequest<{token:string;organization:unknown;user:unknown}>("/team/invitations/"+encodeURIComponent(token)+"/accept",{method:"POST",body:JSON.stringify({password,password_confirmation:confirmation})});localStorage.setItem("token",r.token);localStorage.setItem("organization",JSON.stringify(r.organization));localStorage.setItem("user",JSON.stringify(r.user));navigate("/manager/dashboard",{replace:true})}catch(e){setError(e instanceof Error?e.message:"Could not accept the invitation.")}finally{setSaving(false)}}
 const orgInitial=invitation?.organization.name?.slice(0,2).toUpperCase()||"PM";
 return <div className="ai-root"><style>{styles}</style><div className="ai-card">{loading?<p className="ai-copy">Checking your invitation…</p>:invitation?<><div className="ai-brand"><span className="ai-logo">{invitation.organization.logo_url?<img src={invitation.organization.logo_url} alt=""/>:orgInitial}</span><div><p className="ai-eyebrow">Organization</p><p className="ai-org">{invitation.organization.name}</p></div></div><h1 className="ai-title">Welcome, {invitation.employee.name}</h1><p className="ai-copy">You have been invited to join this organization as a team member. Create your password below to activate your account.</p><span className="ai-role">{invitation.employee.role.replace(/_/g," ")}</span>{error&&<div className="ai-alert"><AlertCircle/><span>{error}</span></div>}<form onSubmit={submit}><div className="ai-field"><label htmlFor="invite-password">Password</label><input id="invite-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></div><div className="ai-field"><label htmlFor="invite-confirmation">Confirm password</label><input id="invite-confirmation" type="password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="new-password"/></div><button className="ai-submit" type="submit" disabled={saving}>{saving?"Activating account…":"Accept invitation"}</button></form></>:<><LockKeyhole style={{width:"2rem",height:"2rem",color:"#82463f"}}/><h1 className="ai-title" style={{marginTop:".8rem"}}>Invitation unavailable</h1><p className="ai-copy">{error||"This invitation is invalid or expired."}</p><button className="ai-submit" type="button" onClick={()=>navigate("/login")}>Go to login</button></>}</div></div>
}
export default AcceptInvitePage;
