import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { BookOpen, Search, ShieldCheck, Scale, ChevronRight } from "lucide-react";

type Section = { title: string; audience: string; body: string };
const terms: Section[] = [
 { title: "1. Agreement, acceptance and eligibility", audience: "Both tenants and property managers", body: "These Terms govern access to and use of the property-management software, its web portals, documentation, integrations and related features (the Platform). By creating an account, accepting an invitation, signing in or using the Platform, you agree to these Terms and the Privacy Policy. If you use the Platform for a company, property owner or other organisation, you confirm that you are authorised to bind that organisation. Do not use the Platform if you do not agree. You must provide accurate information, keep it current and use the Platform only for lawful purposes." },
 { title: "2. Separate roles and responsibilities", audience: "Both; role-specific duties below", body: "The Platform provides tools for property owners, administrators, property managers, authorised staff and tenants. Features and access depend on account role, permissions, organisation configuration and subscription status. Property managers are responsible for their organisation, properties, units, leases, rent schedules, notices, staff permissions and instructions. Tenants are responsible for information they submit, protecting their account and checking their tenancy documents and payment instructions with their property manager. The Platform does not replace the tenancy agreement or create a landlord–tenant relationship between the software developers and a user." },
 { title: "3. Paid plans and unit-based pricing", audience: "Property managers / owners / organisations", body: "The Platform is not a free service for property managers. Paid tiers may differ by features, support, limits and billing frequency. The entry-level price is KES 100 per unit, subject to the plan description shown at purchase, the definition of billable units, any minimums, applicable taxes and any clearly disclosed promotional terms. The final price, billing period, renewal terms, payment due date and included features must be reviewed before purchase. Do not assume a feature is included unless the selected plan says so. Unpaid, overdue or cancelled subscriptions may lead to notices, restricted paid features or suspension, subject to applicable law and any stated grace period. Contact the platform operator for billing disputes before initiating a chargeback where reasonably possible." },
 { title: "4. Rent, deposits, bills, taxes and payment processing", audience: "Both; configuration responsibility rests with property managers", body: "The Platform is a record-keeping, workflow and integration tool. The developers and Platform do not take custody of, hold, escrow, receive, safeguard or disburse rent, tenant deposits, utility bills, service charges, taxes or other payments merely because a payment is recorded or an integration is displayed. Payment movement, if available, is performed by the relevant bank, mobile-money provider, payment gateway or merchant account under its own terms. Property owners/organisations are solely responsible for choosing, owning and configuring the correct Till, PayBill, shortcode, account/reference format, bank account, merchant credentials, callbacks, reconciliation rules, tax details and refund process. If a property manager supplies a wrong Till or PayBill, incorrect account number, wrong credentials, wrong payment destination or inaccurate instructions, the developers are not responsible for funds sent to the wrong destination, failed or delayed transactions, duplicate payments, lost funds, penalties, missed deadlines or resulting disputes, to the maximum extent permitted by law. Verify payment instructions independently before publishing them and test configurations before going live. Tenants should confirm unusual or changed payment instructions directly with their known property management contact before paying." },
 { title: "5. No tax, legal, accounting or financial advice", audience: "Both; especially property managers", body: "Reports, ledgers, exports, reminders and calculations are provided as operational aids, not professional tax, legal, accounting, investment or financial advice. The Platform does not file tax returns or pay KRA or any other tax authority on your behalf unless a separately documented, authorised service expressly says otherwise. It does not guarantee that records meet every statutory, audit, lease, county, tax or regulatory requirement. Property owners and organisations remain responsible for determining tax treatment, filing returns, remitting taxes, obtaining professional advice, issuing legally compliant receipts and meeting deadlines. Users must independently verify totals and source records before relying on reports or submitting them to KRA, a court, an auditor, a bank or another third party." },
 { title: "6. Accuracy of data and user decisions", audience: "Both; data entry primarily by managers and authorised staff", body: "You are responsible for reviewing information entered, imported, generated or changed through your account. Incorrect property details, unit status, rent, lease dates, tenant identity, balances, payment references, expenses, maintenance records or notices can produce incorrect results. The Platform may contain delays, rounding, integration errors, unavailable services or incomplete data. Review transaction statuses against the originating provider and reconcile records regularly. Do not treat a pending callback, screenshot, notification or unverified tenant entry as proof that funds cleared. Keep appropriate independent records where needed." },
 { title: "7. Account security and authorised staff", audience: "Both; organisation administrators have additional duties", body: "Keep passwords, one-time codes, recovery methods, devices, API credentials and access tokens confidential. Do not share accounts. Notify the platform operator promptly if you suspect unauthorised access. Organisation administrators must grant staff only the permissions they need, promptly remove access when roles change or employment ends, review sensitive activity and ensure staff are trained. Actions performed through your authenticated account may be attributed to you unless evidence shows otherwise. Never place secrets or payment credentials in support tickets or public messages." },
 { title: "8. Acceptable use and prohibited conduct", audience: "Both", body: "Do not use the Platform to defraud, harass, threaten, discriminate unlawfully, stalk, impersonate, infringe rights, upload malicious code, probe systems without permission, bypass access controls, scrape or overload services, manipulate payment records, forge receipts, unlawfully disclose personal data or interfere with other users. Do not use tenant or property data for unrelated marketing or other purposes without a lawful basis. We may investigate credible misuse, preserve relevant records and restrict access where reasonably necessary for security, legal compliance or protection of users." },
 { title: "9. Third-party services and availability", audience: "Both", body: "Google authentication, mobile-money services, banks, payment gateways, email, hosting and other integrations are operated by third parties and may have separate terms, outages, rate limits, security controls or fees. The Platform cannot guarantee uninterrupted operation or the availability, accuracy or security of a third-party service. Authentication availability may depend on valid OAuth credentials, authorised redirect URIs, domain settings, provider policy, server session/cookie configuration and correct production environment variables. Users and organisation administrators must not circumvent provider safeguards." },
 { title: "10. Maintenance, changes and service limits", audience: "Both", body: "We may update, repair, secure, improve or discontinue features, and may perform planned or emergency maintenance. We aim to minimise disruption but do not promise continuous, error-free access. We may change plans or prices prospectively with reasonable notice where required by law or the applicable purchase terms. Material feature changes may require updated documentation, user retraining or configuration review. We will not intentionally remove user data as a routine substitute for a proper migration; however, users should maintain lawful exports and backups appropriate to their needs." },
 { title: "11. Data ownership, licence and confidentiality", audience: "Both", body: "As between the parties, users or their organisations retain rights they hold in content they submit. You grant the Platform operator a limited licence to host, process, transmit, display and back up that content as needed to operate, secure, support and improve the service and meet legal obligations. You must have the rights and legal authority to submit the data. Do not upload information about tenants, employees or other people unless you have an appropriate legal basis and have provided any required notices. Confidentiality and data-protection obligations remain subject to applicable law." },
 { title: "12. Suspension and termination", audience: "Both", body: "You may stop using the Platform and request account or subscription closure through the available account or support process. Organisations should plan data exports and resolve outstanding subscription obligations before closure. We may suspend or limit access where reasonably necessary for unpaid fees, security threats, suspected fraud, unlawful use, provider requirements or legal orders. Where practicable, we will provide notice and an opportunity to remedy the issue. Some records may need to be retained for security, dispute resolution, accounting or legal compliance, subject to the Privacy Policy and applicable law." },
 { title: "13. Disclaimers and limitation of liability", audience: "Both", body: "To the maximum extent permitted by applicable law, the Platform is provided on an as-available basis and without warranties that it will be uninterrupted, error-free, suitable for every purpose or guarantee any financial, occupancy, compliance or business result. The developers are not liable for indirect, incidental, special, consequential or punitive loss, lost profits, lost opportunity, reputational harm, data loss, payment-provider failures, incorrect merchant configuration, user-entered errors, disputes between landlords and tenants, tax penalties, or decisions made solely from unverified Platform records. Nothing in these Terms excludes or limits liability that cannot lawfully be excluded or limited, including any non-waivable consumer rights. Where liability may lawfully be limited, the applicable limit will be the amount paid for the affected Platform service during the three months before the event, except where a different mandatory legal rule applies." },
 { title: "14. Indemnity", audience: "Primarily property managers / organisations; subject to applicable law", body: "To the extent permitted by law, an organisation using the Platform agrees to defend and indemnify the Platform operator and its developers against third-party claims, losses, liabilities and reasonable costs arising from its unlawful use, its breach of these Terms, its payment destination or merchant configuration, its tenancy or property-management decisions, its failure to obtain required rights or notices, or data it submits, except to the extent caused by the indemnified party's own liability that cannot lawfully be shifted. This clause does not remove rights or remedies that applicable law makes non-waivable." },
 { title: "15. Complaints, disputes and governing law", audience: "Both", body: "Please first contact the property manager for tenancy, rent, maintenance or property-specific disputes, and contact Platform support for technical, account or subscription matters. We may request transaction references, timestamps and relevant screenshots; redact passwords, identity numbers and full payment credentials. These Terms are intended to be interpreted consistently with the laws of Kenya and applicable data-protection and consumer-protection requirements. Any mandatory jurisdiction, tribunal, regulator or consumer remedy under applicable law remains available." },
 { title: "16. Updates and contact", audience: "Both", body: "We may update these Terms as the Platform, law or integrations change. The current version will be published here with its revision date. Continued use after an effective update constitutes acceptance only to the extent permitted by law; where fresh consent is legally required, we will request it. Contact the Platform operator through the support channel supplied in the app for questions about these Terms." }
];
const privacy: Section[] = [
 { title: "1. Scope and who is responsible", audience: "Both tenants and property managers", body: "This Privacy Policy describes how personal information may be processed when you use the property-management Platform. The property owner, landlord or management organisation generally decides why and how tenancy information is used and may act as the data controller for that information. The Platform operator may process that information on the organisation's instructions to provide hosting, account access, records, communications and support, and may separately control limited account, billing, security and service-operation data. Actual roles depend on the processing activity and applicable law, including Kenya's Data Protection Act, 2019 and regulations. Organisations must provide their own required tenant privacy notices and determine their lawful basis." },
 { title: "2. Information that may be collected", audience: "Both; tenants may provide additional tenancy information", body: "Depending on enabled features, information may include name, email, phone number, username, authentication-provider identifier, profile image, role, organisation membership, login/security events, property and unit details, lease dates, rent and deposit records, payment references and statuses, expenses, maintenance requests, messages, notifications, audit events, support enquiries and subscription/billing metadata. Tenant or lease forms may also contain identity details, residential or postal address, employer and next-of-kin details. Only collect or submit fields that are necessary and lawful for the relevant purpose. Payment credentials and secrets should be stored only through supported secure configuration flows, never in free-text notes." },
 { title: "3. Purposes and lawful grounds", audience: "Both; organisations must assess their own processing", body: "Information may be used to authenticate users, create and administer accounts, assign permissions, manage properties and tenancies, record and reconcile payments, track maintenance, deliver notifications, provide support, prevent fraud, secure the Platform, diagnose failures, maintain audit trails, administer subscriptions, meet legal obligations and resolve disputes. Depending on context, processing may rely on contract, legitimate interests, legal obligation, consent or another lawful basis available under applicable law. Consent is not assumed where another basis is required or more appropriate. Organisations are responsible for documenting their lawful basis and respecting data-subject rights." },
 { title: "4. Google sign-in and authentication data", audience: "Both", body: "If you choose Google sign-in, Google provides identity information permitted by the consent screen and configured scopes, typically a provider identifier, email address, name and possibly profile image. The Platform uses this information to authenticate you and link the provider identity to the correct account or guide you through account registration. Google handles its own data under its own privacy terms. Do not assume that signing in with Google automatically grants access to a property or tenant record; access must still follow Platform account and role rules. Protect your Google account and review connected-app permissions in Google settings." },
 { title: "5. Payment information and financial records", audience: "Both; configuration and merchant records primarily property managers", body: "The Platform may store payment references, amounts, timestamps, statuses, reconciliation results, receipts or limited transaction metadata needed for records and matching. Actual card, bank or mobile-money processing may be handled by the relevant third-party provider. Organisation-specific merchant credentials, if supported, should be encrypted and accessible only to authorised roles. Do not send full passwords, PINs, secret keys or unnecessary financial information through support. Property managers must confirm their lawful basis and provide clear notices for rent, deposit, utility and employee financial records." },
 { title: "6. Sharing and service providers", audience: "Both", body: "Information may be made available to authorised users within the relevant organisation according to role permissions, and to service providers needed for hosting, storage, authentication, email, monitoring, payment integrations or support. Information may also be disclosed where required by law, a valid legal process, protection of rights, investigation of suspected abuse, or a business transfer subject to appropriate safeguards. We do not sell personal data as a product. Third-party providers may process information under their own terms and privacy policies." },
 { title: "7. International transfers and security", audience: "Both", body: "Hosting and service providers may process information in Kenya or other countries. Where personal data is transferred across borders, the responsible party must apply safeguards and meet requirements under applicable data-protection law. Security measures may include access controls, role permissions, encryption in transit, protected credential storage, audit logging, backups and monitoring. No online service can guarantee absolute security. Users must keep credentials private, use secure devices and promptly report suspected compromise. Do not include sensitive personal data in public bug reports." },
 { title: "8. Retention and deletion", audience: "Both; organisations decide retention for tenancy records", body: "Personal information is retained only for as long as reasonably necessary for the stated purpose, contractual service, security, accounting, dispute resolution or legal obligations, subject to applicable law. Property organisations must set appropriate retention periods for leases, payments, tenant screening, maintenance and employment records. Closing an account does not necessarily immediately erase all information, since some records may need to remain for legal, audit, backup or security reasons. Deletion requests will be assessed against applicable rights, legal obligations and the Platform's role in the processing." },
 { title: "9. Your rights and how to exercise them", audience: "Both; requests about tenancy records may need to go to the organisation", body: "Subject to applicable law, individuals may have rights to be informed, access personal data, correct inaccurate data, request deletion, object to or restrict certain processing, withdraw consent where processing relies on consent, request portability, and complain to the relevant data-protection authority. Contact your property manager or organisation first for records they control; contact Platform support for account or service-operation data. We may need to verify identity and may refer a request to the responsible controller. Legal exceptions and limitations may apply." },
 { title: "10. Children and sensitive information", audience: "Both", body: "The Platform is intended for property-management and tenancy use, not for children to independently create accounts unless a lawful, specifically supported process exists. Do not submit children's information or sensitive personal data unless it is necessary, lawful and appropriately protected. Organisations must take additional care where information concerns minors, identity documents, next of kin or other potentially sensitive categories." },
 { title: "11. Cookies, sessions and diagnostics", audience: "Both", body: "The Platform may use browser storage, session cookies or similar mechanisms to keep you signed in, protect authentication flows, remember settings and diagnose errors. Blocking or clearing them may disrupt login or preferences. Technical logs may include IP/device/browser details, request timestamps, error information and security events. We aim to collect only what is reasonably needed for security, operation and troubleshooting." },
 { title: "12. Policy updates and contact", audience: "Both", body: "This Policy may change as features, service providers or legal requirements change. The current version and revision date will be published here. Where required, users will be notified or asked to provide renewed consent. For a privacy request, identify the account and organisation involved, describe the request, and avoid sending passwords, PINs or full payment credentials. Use the support channel displayed in the Platform." }
];
const helpSections: Section[] = [
 {title:"Getting started and choosing your portal",audience:"Both",body:"Sign in using your account email or username and password, or use Google if your account is linked to that Google identity. The Platform routes you according to your assigned role. Property owners, admins, property managers and staff use the manager portal; tenants use the tenant portal. If you land in the wrong portal, sign out and contact your organisation administrator to confirm your role."},
 {title:"Google sign-in troubleshooting",audience:"Both",body:"Use the same Google account linked to your Platform account. If sign-in returns an error, retry once, check that cookies are enabled, confirm your device date/time, and avoid private browsing if your browser blocks the authentication session. If you are a new user, your organisation may need to invite or register you first. If the issue persists, send support the approximate time, portal, browser/device and exact non-sensitive error. Never send passwords or verification codes."},
 {title:"Username and profile",audience:"Both",body:"Your generated or assigned username is shown after first sign-in when the account flow provides it and remains available from your profile. Save it securely; you can also use your registered email to sign in where supported. If the username is missing or appears incorrect, contact your organisation administrator rather than creating a duplicate account."},
 {title:"Manager dashboard and navigation",audience:"Property owners, admins, managers and staff",body:"The dashboard summarises activity available to your role. Use Properties to maintain property records, Units to manage unit status and details, Tenants to manage tenant records, Leases for tenancy dates and terms, Payments to record and review receipts, Reconciliation to match provider transactions, Expenses for costs, and Maintenance to track repair requests. Cards and menu items may vary by permissions and subscription. Open a record to view details before editing it."},
 {title:"Properties, units and tenant records",audience:"Property owners, admins, managers and authorised staff",body:"Keep property addresses, units, occupancy status, rent amounts and tenant contact details accurate. Check the property and unit before attaching a lease or tenant. Do not mark a unit available if it is occupied or under maintenance. Correct mistakes promptly and ensure you are authorised to view or change personal information."},
 {title:"Leases, rent, deposits and payment reconciliation",audience:"Property owners, admins, managers and authorised staff; tenants for their own records",body:"A payment entry or screenshot is not necessarily proof of settlement. Compare payment references and status with the original provider statement and investigate unmatched or duplicate transactions. Confirm merchant destination, Till/PayBill and account reference before telling tenants where to pay. The Platform does not itself hold rent or guarantee that a transfer reached the intended recipient. Contact your bank/mobile-money provider for a provider-side transaction dispute and your property manager for tenancy ledger questions."},
 {title:"M-Pesa Till, PayBill and payment settings",audience:"Property owners and authorised organisation administrators",body:"Only authorised owners/admins should configure merchant destinations and credentials. Verify the Till/PayBill ownership, account/reference rules, callback configuration, credentials and test transaction before enabling a destination. Never share PINs or secret keys. A wrong destination may route money outside the intended organisation and the developers cannot reverse a payment made to an incorrect destination. Contact the relevant payment provider immediately if funds were sent incorrectly."},
 {title:"Maintenance requests",audience:"Both; tenants submit requests and managers coordinate responses",body:"Tenants should describe the issue, location, urgency and safe access arrangements without including unnecessary sensitive information. Attach photos only when useful and avoid images containing identity documents or unrelated people. Managers should acknowledge, assign and update requests, record relevant work and communicate delays. For immediate threats to life or safety, contact local emergency services rather than relying on an in-app request."},
 {title:"Staff, permissions and audit activity",audience:"Property owners and authorised administrators",body:"Invite only trusted staff, assign the least privilege needed, review permissions regularly and deactivate accounts promptly when access is no longer appropriate. Financial changes such as edits, voids, refunds or adjustments should follow the organisation's approval controls and documented process. Review available audit activity when investigating unexpected changes. Never share an administrator login."},
 {title:"Search and filters",audience:"Both",body:"Use the search field on the page you are viewing and enter a distinctive name, email, property, unit, reference or status supported by that page. Clear the query to restore the full list. Some results may be limited to your role, organisation, current filters or loaded records. If you expect a record that does not appear, verify filters and permissions, then refresh. Do not assume a search result is complete if the page indicates loading or an error."},
 {title:"Profile, password and account safety",audience:"Both",body:"Keep your email and contact details current. Use a unique, strong password and do not share one-time codes. If you suspect compromise, change your password, sign out of other sessions where supported and contact the organisation administrator or support. Google account security is managed partly through Google. If you cannot access the email on your account, request identity verification through the appropriate support channel."},
 {title:"Subscriptions and billing",audience:"Property owners, admins and billing contacts",body:"Review your selected tier, billable unit count, billing frequency, due date and included features before purchase. The entry tier starts at KES 100 per unit; your actual charge depends on the plan and terms presented at checkout. Keep billing contacts current and contact support with the invoice or subscription reference if a charge appears wrong. Subscription fees are separate from rent, taxes, utility bills and payment-provider charges."},
 {title:"Privacy, terms and support",audience:"Both",body:"Read the Terms and Privacy Policy pages for responsibilities, payment configuration risks, data handling and user rights. Tenants should normally contact their property manager about rent, lease or maintenance matters; contact Platform support for sign-in, account, subscription or technical issues. Include the page, action, approximate time and non-sensitive error details. Never send passwords, M-Pesa PINs, API secrets or complete identity documents through general support."}
];
const allHelp = helpSections;
export default function LegalHelpPage({initialTab = "help"}: {initialTab?: "help" | "terms" | "privacy"}) {
 const [tab,setTab]=useState<"help"|"terms"|"privacy">(initialTab);
 const [query,setQuery]=useState("");
 const data=tab==="terms"?terms:tab==="privacy"?privacy:allHelp;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?data.filter(s=>(s.title+" "+s.audience+" "+s.body).toLowerCase().includes(q)):data},[data,query]);
 return <main style={{minHeight:"100vh",background:"var(--pms-bg, #f7f8fb)",color:"var(--pms-text, #172033)",padding:"clamp(1rem,4vw,3rem)",overflowWrap:"anywhere"}}>
  <div style={{maxWidth:1000,margin:"0 auto"}}>
   <header style={{marginBottom:"1.5rem"}}><Link to="/" style={{color:"var(--pms-accent, #2459c4)",textDecoration:"none",fontSize:".9rem"}}>← Property Management System</Link><h1 style={{fontSize:"clamp(2rem,5vw,3rem)",margin:"1rem 0 .5rem"}}>{tab==="terms"?"Terms of Service":tab==="privacy"?"Privacy Policy":"Help Centre & User Manual"}</h1><p style={{maxWidth:760,lineHeight:1.7,color:"var(--pms-muted, #4b5568)"}}>Practical guidance for property owners, administrators, managers, staff and tenants. Content may be updated as features change. Last reviewed: 10 October 2026.</p></header>
   <nav aria-label="Help and policies" style={{display:"flex",gap:".5rem",flexWrap:"wrap",marginBottom:"1rem"}}>{([{id:"help",label:"Help & manual",icon:BookOpen},{id:"terms",label:"Terms of service",icon:Scale},{id:"privacy",label:"Privacy policy",icon:ShieldCheck}] as const).map(item=><button key={item.id} onClick={()=>{setTab(item.id);setQuery("")}} style={{display:"inline-flex",alignItems:"center",gap:".5rem",padding:".75rem 1rem",borderRadius:12,border:"1px solid "+(tab===item.id?"var(--pms-accent, #2459c4)":"var(--pms-border, #d8deea)"),background:tab===item.id?"var(--pms-accent-soft, #eaf0ff)":"var(--pms-surface, #fff)",color:tab===item.id?"var(--pms-accent, #2459c4)":"var(--pms-text, #172033)",cursor:"pointer"}}><item.icon size={17}/>{item.label}</button>)}</nav>
   <label style={{display:"flex",alignItems:"center",gap:".75rem",padding:"0 1rem",border:"1px solid var(--pms-border, #d8deea)",borderRadius:12,background:"var(--pms-surface, white)",color:"var(--pms-text, #172033)",marginBottom:"1rem",minWidth:0}}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==="help"?"Search the user manual…":"Search this document…"} aria-label="Search content" style={{border:0,outline:0,padding:"1rem 0",width:"100%",fontSize:"1rem",background:"transparent",color:"var(--pms-text, #172033)",minWidth:0}}/></label>
   <p style={{fontSize:".85rem",color:"var(--pms-muted, #4b5568)"}}>{filtered.length} section{filtered.length===1?"":"s"} · Audience is labelled on every section.</p>
   <div style={{display:"grid",gap:".75rem"}}>{filtered.map(section=><details key={section.title} open={Boolean(query)} style={{background:"var(--pms-surface, white)",color:"var(--pms-text, #172033)",border:"1px solid var(--pms-border, #e0e5ee)",borderRadius:14,padding:"clamp(.9rem,2.5vw,1.2rem)",boxShadow:"var(--pms-shadow, 0 2px 8px #14213d08)",minWidth:0}}><summary style={{cursor:"pointer",fontWeight:700,lineHeight:1.5,listStyle:"none",display:"flex",gap:".75rem",alignItems:"flex-start",color:"var(--pms-heading, #172033)"}}><ChevronRight size={18} style={{flex:"none",marginTop:3}}/><span style={{flex:1}}>{section.title}<small style={{display:"block",fontWeight:500,color:"var(--pms-muted, #4b5568)",marginTop:".25rem"}}>Applies to: {section.audience}</small></span></summary><p style={{margin:"1rem 0 .25rem",lineHeight:1.8,whiteSpace:"pre-line",color:"var(--pms-text, #172033)"}}>{section.body}</p></details>)}</div>
   {filtered.length===0&&<p role="status" style={{padding:"2rem",textAlign:"center"}}>No matching sections. Try another keyword or clear your search.</p>}
   <footer style={{marginTop:"2rem",paddingTop:"1rem",borderTop:"1px solid var(--pms-border, #d8deea)",fontSize:".9rem",lineHeight:1.7,color:"var(--pms-muted, #4b5568)"}}><p><strong>Important:</strong> These pages are product information, not a substitute for review by a qualified Kenyan lawyer or data-protection professional. Before production launch, have the final legal terms, subscription checkout disclosures, privacy contacts, retention periods and complaint process reviewed and completed for the actual operating entity.</p><div style={{display:"flex",gap:"1rem",flexWrap:"wrap"}}><Link to="/terms">Terms</Link><Link to="/privacy">Privacy</Link><Link to="/help">Help centre</Link><Link to="/login">Sign in</Link></div></footer>
  </div>
 </main>;
}
