import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import TenantDashboardLayout from "../../layouts/TenantDashboardLayout";
import { apiRequest, downloadFile } from "../../services/api";
import {
  ArrowRight,
  BadgeCheck,
  CheckCircle2,
  Clock,
  FileSignature,
  FileText,
  Info,
  Loader2,
  ShieldCheck,
} from "lucide-react";

const styles = `
.tl-page { --tl-ink:#111318; --tl-muted:#68707d; --tl-line:#e7e9ed; --tl-soft:#f7f7f5; --tl-gold:#b48a42; --tl-gold-soft:#fbf6eb; --tl-green:#1f7a55; --tl-green-soft:#edf8f2; }
.tl-stack{display:flex;flex-direction:column;gap:1.25rem;max-width:1180px;margin:0 auto;padding-bottom:2rem}
.tl-hero{position:relative;overflow:hidden;padding:1.8rem 1.8rem 1.55rem!important;border:1px solid #dedfe2!important;border-radius:24px!important;background:linear-gradient(135deg,#17181c 0%,#24262b 55%,#111214 100%)!important;color:#fff;box-shadow:0 22px 55px -40px rgba(0,0,0,.55)}
.tl-hero:after{content:"";position:absolute;width:280px;height:280px;border-radius:50%;right:-110px;top:-145px;background:rgba(180,138,66,.14);filter:blur(2px)}
.tl-hero__content{position:relative;z-index:1;display:flex;align-items:flex-start;justify-content:space-between;gap:1.5rem}
.tl-eyebrow{margin:0 0 .45rem;font-size:.68rem;line-height:1;text-transform:uppercase;letter-spacing:.16em;font-weight:800;color:#d6b777}
.tl-hero h2{margin:0;font-size:1.65rem;line-height:1.15;letter-spacing:-.035em;font-weight:760;color:#fff}
.tl-hero__sub{margin:.5rem 0 0;color:#b9bec7;font-size:.82rem;line-height:1.5}
.tl-hero__badges{display:flex;align-items:center;justify-content:flex-end;gap:.5rem;flex-wrap:wrap}
.tl-badge{display:inline-flex;align-items:center;gap:.38rem;width:max-content;padding:.4rem .7rem;border-radius:999px;font-size:.7rem;font-weight:750;white-space:nowrap}
.tl-badge svg{width:.9rem;height:.9rem}
.tl-badge--dark{background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.12);color:#f3f4f6}
.tl-badge--gold{background:#2e271b;border:1px solid #5d4b2b;color:#e6c98d}
.tl-badge--done{background:var(--tl-green-soft);color:var(--tl-green);border:1px solid #cde9da}
.tl-badge--pending{background:#fff7e5;color:#956b21;border:1px solid #f1ddb2}
.tl-overview{display:flex;flex-direction:column;gap:0!important;padding:0!important;overflow:hidden;border:1px solid #dedfe2!important;border-radius:22px!important;background:#fff!important;box-shadow:0 14px 40px -34px rgba(16,24,40,.45)}
.tl-section-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.2rem 1.35rem;border-bottom:1px solid var(--tl-line)}
.tl-section-head h3{margin:0;color:var(--tl-ink);font-size:.92rem;font-weight:780;letter-spacing:-.015em}.tl-section-head p{margin:.25rem 0 0;color:var(--tl-muted);font-size:.72rem}
.tl-section-label{display:flex;align-items:center;gap:.45rem;color:#8b6b31;font-size:.66rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.tl-section-label svg{width:.85rem;height:.85rem}
.tl-parties{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-bottom:1px solid var(--tl-line)}.tl-party{padding:1.1rem 1.35rem;min-width:0}.tl-party+.tl-party{border-left:1px solid var(--tl-line)}
.tl-label{display:block;margin:0;color:#8a919d;font-size:.63rem;font-weight:800;text-transform:uppercase;letter-spacing:.09em}.tl-value{display:block;margin:.32rem 0 0;color:var(--tl-ink);font-size:.88rem;font-weight:740;line-height:1.35}
.tl-timeline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid var(--tl-line)}.tl-date{position:relative;min-width:0;padding:1.15rem 1.2rem 1.25rem}.tl-date+.tl-date{border-left:1px solid var(--tl-line)}.tl-date--official{background:linear-gradient(180deg,#fffdf8,#fff)}
.tl-date__dot{width:.45rem;height:.45rem;border-radius:50%;background:#c4c8ce;margin-bottom:.65rem}.tl-date--official .tl-date__dot{background:var(--tl-gold);box-shadow:0 0 0 4px #fbf5e9}.tl-date__value{display:block;margin-top:.35rem;color:var(--tl-ink);font-size:.92rem;font-weight:760;line-height:1.25}.tl-date__hint{display:block;margin-top:.28rem;color:#9096a0;font-size:.66rem;line-height:1.35}
.tl-end-editor{display:flex;align-items:flex-end;gap:.45rem;margin-top:.55rem}.tl-end-editor input{width:100%;min-width:0;padding:.52rem .55rem;border:1px solid #d9c69e;border-radius:9px;background:#fffdf8;color:var(--tl-ink);font:inherit;font-size:.72rem;outline:none}.tl-end-editor input:focus{border-color:var(--tl-gold);box-shadow:0 0 0 3px rgba(180,138,66,.12)}
.tl-icon-save{display:inline-flex;align-items:center;justify-content:center;flex:none;width:2rem;height:2rem;border:1px solid #d9c69e;border-radius:9px;background:#fff8e9;color:#8d682c;cursor:pointer}.tl-icon-save:disabled{opacity:.55;cursor:wait}.tl-icon-save svg{width:.85rem;height:.85rem}.tl-message{margin:.55rem 0 0;font-size:.68rem;line-height:1.4;color:var(--tl-green)}
.tl-financials{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.tl-financial{padding:1.15rem 1.35rem}.tl-financial+.tl-financial{border-left:1px solid var(--tl-line)}.tl-financial strong{display:block;margin-top:.3rem;color:var(--tl-ink);font-size:1.12rem;font-weight:780;letter-spacing:-.02em}
.tl-info{display:flex;align-items:flex-start;gap:.55rem;margin:0 1.35rem 1.2rem;padding:.8rem .9rem;border-radius:12px;background:#f5f7f9;color:#737b87}.tl-info svg{flex:none;width:.9rem;height:.9rem;margin-top:.08rem;color:#87909c}.tl-info p{margin:0;font-size:.68rem;line-height:1.55}
.tl-deposit{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.15rem 1.3rem!important;border:1px solid #e2e4e7!important;border-radius:18px!important;background:linear-gradient(100deg,#fffdf8,#fff)!important}.tl-deposit__main{min-width:0}.tl-deposit__amount{margin:.3rem 0 0;color:var(--tl-ink);font-size:.88rem;font-weight:720}.tl-deposit__status{margin:.28rem 0 0;color:var(--tl-muted);font-size:.69rem;line-height:1.4}.tl-deposit__action{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;flex:none;border:0;border-radius:9px;padding:.6rem .8rem;background:#17181b;color:#fff;font:inherit;font-size:.68rem;font-weight:780;cursor:pointer}.tl-deposit__action:disabled{opacity:.55;cursor:wait}.tl-deposit__action svg{width:.8rem;height:.8rem}
.tl-status{display:flex;align-items:center;gap:1rem;padding:1rem 1.25rem;border-radius:16px;border:1px solid #e0e4e8;background:#fff}.tl-status__icon{display:flex;align-items:center;justify-content:center;flex:none;width:2.45rem;height:2.45rem;border-radius:12px;background:#f4f5f6;color:#59616c}.tl-status__icon svg{width:1.05rem;height:1.05rem}.tl-status strong{display:block;color:var(--tl-ink);font-size:.8rem}.tl-status p{margin:.2rem 0 0;color:var(--tl-muted);font-size:.68rem;line-height:1.45}
.tl-complete{padding:1.35rem!important;border:1px solid #cde9da!important;border-radius:18px!important;background:linear-gradient(135deg,#f5fcf8,#fff)!important}.tl-complete__top{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.tl-complete h3{margin:0;color:var(--tl-ink);font-size:.95rem}.tl-complete p{margin:.35rem 0 0;color:var(--tl-muted);font-size:.7rem;line-height:1.5}.tl-download{display:flex;align-items:center;justify-content:space-between;gap:.8rem;width:100%;margin-top:1rem;padding:.78rem 1rem;border:1px solid #cde1d6;border-radius:11px;background:#fff;color:var(--tl-green);font:inherit;font-size:.75rem;font-weight:780;cursor:pointer}.tl-download:hover{background:#f7fcf9}.tl-download svg{width:.9rem;height:.9rem}.tl-download:disabled{opacity:.6;cursor:wait}
.tl-docs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.tl-doc{display:flex;flex-direction:column;min-width:0;padding:1.15rem!important;border:1px solid #e0e2e5!important;border-radius:20px!important;background:#fff!important;box-shadow:0 14px 40px -38px rgba(16,24,40,.55)}
.tl-doc__head{display:flex;align-items:flex-start;justify-content:space-between;gap:.8rem;margin-bottom:.85rem}.tl-doc__title{display:flex;align-items:center;gap:.55rem;min-width:0}.tl-doc__title-icon{display:flex;align-items:center;justify-content:center;flex:none;width:2rem;height:2rem;border-radius:9px;background:#f4f1ea;color:#8b6b31}.tl-doc__title-icon svg{width:.9rem;height:.9rem}.tl-doc h3{margin:0;color:var(--tl-ink);font-size:.85rem;font-weight:780}.tl-doc__sub{margin:.18rem 0 0;color:#9298a1;font-size:.64rem}
.tl-doc textarea{width:100%;min-height:20rem;resize:vertical;box-sizing:border-box;border:1px solid #e4e6e9;border-radius:13px;padding:1rem;background:#fafafa;color:#333941;font:inherit;font-size:.78rem;line-height:1.7;outline:none}.tl-doc textarea:focus{border-color:#c9a96c;box-shadow:0 0 0 3px rgba(180,138,66,.09)}.tl-doc textarea:disabled{background:#fafafa;color:#5f6670}
.tl-signed{display:flex;align-items:center;gap:.7rem;margin-top:.75rem;padding:.7rem .8rem;border:1px solid #d5eadf;border-radius:11px;background:#f6fbf8}.tl-signed__initials{font-size:1rem;font-weight:850;letter-spacing:.08em;color:var(--tl-ink)}.tl-signed__meta{min-width:0}.tl-signed__stamp{display:block;color:var(--tl-green);font-size:.58rem;font-weight:850;letter-spacing:.1em}.tl-signed__date{display:block;margin-top:.12rem;color:#7d8782;font-size:.63rem}.tl-doc__hint{margin:.7rem 0 0;color:#8b929b;font-size:.66rem;line-height:1.5}
.tl-date-card{margin-bottom:.8rem;padding:.85rem;border:1px solid #e5e1d8;border-radius:13px;background:#fcfaf5}.tl-date-card__title{margin:0;color:var(--tl-ink);font-size:.72rem;font-weight:780}.tl-date-card__hint{margin:.25rem 0 .7rem;color:#858b94;font-size:.64rem;line-height:1.45}.tl-date-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.tl-date-field{display:flex;flex-direction:column;gap:.3rem}.tl-date-field label{font-size:.6rem;font-weight:750;color:#777f89}.tl-date-field input{width:100%;box-sizing:border-box;padding:.52rem .55rem;border:1px solid #dedfe1;border-radius:8px;background:#fff;color:var(--tl-ink);font:inherit;font-size:.68rem}
.tl-actions{display:flex;align-items:center;justify-content:space-between;gap:.8rem;margin-top:.85rem;padding-top:.85rem;border-top:1px solid var(--tl-line)}.tl-sign{display:flex;align-items:center;gap:.5rem;flex-wrap:wrap}.tl-sign label{color:#737b85;font-size:.64rem;font-weight:750}.tl-sign input{width:4.5rem;padding:.5rem .55rem;border:1px solid #d9dce0;border-radius:8px;font:inherit;font-size:.7rem;text-transform:uppercase}.tl-sign button,.tl-save{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;border:0;border-radius:9px;padding:.55rem .75rem;font:inherit;font-size:.68rem;font-weight:780;cursor:pointer}.tl-save{background:#f1f2f3;color:#444b54}.tl-sign button{background:#17181b;color:#fff}.tl-sign button:hover{background:#2a2c30}.tl-sign button:disabled,.tl-save:disabled{opacity:.5;cursor:wait}.tl-sign button svg,.tl-save svg{width:.8rem;height:.8rem}.tl-feedback{margin:.65rem 0 0;color:var(--tl-green);font-size:.67rem;line-height:1.4}
.tl-empty{padding:3rem!important;text-align:center}.tl-empty__icon{display:flex;align-items:center;justify-content:center;width:3rem;height:3rem;margin:0 auto 1rem;border-radius:14px;background:#f5f1e8;color:#9a7637}.tl-empty__icon svg{width:1.25rem;height:1.25rem}.tl-skeleton{height:26rem}.tl-spin{animation:tl-rotate .9s linear infinite}@keyframes tl-rotate{to{transform:rotate(360deg)}}
@media(max-width:900px){.tl-timeline{grid-template-columns:repeat(2,minmax(0,1fr))}.tl-docs{grid-template-columns:1fr}}
@media(max-width:620px){.tl-stack{gap:1rem}.tl-hero{padding:1.35rem!important;border-radius:18px!important}.tl-hero__content{flex-direction:column}.tl-hero__badges{justify-content:flex-start}.tl-parties,.tl-financials{grid-template-columns:1fr}.tl-party+.tl-party,.tl-financial+.tl-financial{border-left:0;border-top:1px solid var(--tl-line)}.tl-timeline{grid-template-columns:1fr}.tl-date+.tl-date{border-left:0;border-top:1px solid var(--tl-line)}.tl-doc{padding:.9rem!important}.tl-date-fields{grid-template-columns:1fr}.tl-actions{align-items:stretch;flex-direction:column}.tl-sign{width:100%}.tl-sign input{flex:1}.tl-sign button{flex:1}.tl-deposit{align-items:flex-start;flex-direction:column}.tl-deposit__action{width:100%}}
@media(prefers-reduced-motion:reduce){.tl-spin{animation:none}}
`;

interface DepositInfo { amount_required:number|string|null; amount_paid:number|string|null; status:string|null; tenant_marked_paid_at:string|null }
interface Agreement { lease_id:number; status:string|null; start_date:string|null; end_date:string|null; requested_move_in_date:string|null; requested_move_out_date:string|null; rent_due_day:number; agreement_status:string|null; organization:{id:number;name:string}|null; property:{id:number;name:string;address:string|null;city:string|null}|null; unit:{id:number;unit_number:string;unit_type:string|null;default_rent:number|string|null}|null; monthly_rent:number|string|null; deposit_amount:number|string|null; manager_terms:string|null; tenant_terms:string|null; manager_signature:string|null; manager_signed_at:string|null; tenant_signature:string|null; tenant_signed_at:string|null; agreement_finalized:boolean; deposit:DepositInfo|null }

function asAgreement(payload:unknown):Agreement|null{if(!payload||typeof payload!=="object")return null;const record=payload as Record<string,unknown>;const firstData=record.data&&typeof record.data==="object"?(record.data as Record<string,unknown>):record;const source=firstData.data&&typeof firstData.data==="object"?(firstData.data as Record<string,unknown>):firstData;if(!source||Object.keys(source).length===0)return null;const objectOrNull=(v:unknown)=>v&&typeof v==="object"?v as Record<string,unknown>:null;const organization=objectOrNull(source.organization),property=objectOrNull(source.property),unit=objectOrNull(source.unit),deposit=objectOrNull(source.deposit);return{...source,organization:organization?{id:Number(organization.id),name:String(organization.name??"")}:null,property:property?{id:Number(property.id),name:String(property.name??""),address:property.address==null?null:String(property.address),city:property.city==null?null:String(property.city)}:null,unit:unit?{id:Number(unit.id),unit_number:String(unit.unit_number??""),unit_type:unit.unit_type==null?null:String(unit.unit_type),default_rent:unit.default_rent==null?null:unit.default_rent as number|string}:null,monthly_rent:source.monthly_rent==null?null:source.monthly_rent as number|string,deposit_amount:source.deposit_amount==null?null:source.deposit_amount as number|string,deposit:deposit?{amount_required:deposit.amount_required==null?null:deposit.amount_required as number|string,amount_paid:deposit.amount_paid==null?null:deposit.amount_paid as number|string,status:deposit.status==null?null:String(deposit.status),tenant_marked_paid_at:deposit.tenant_marked_paid_at==null?null:String(deposit.tenant_marked_paid_at)}:null} as unknown as Agreement}
function longDateTime(value:string|null){if(!value)return"";const date=new Date(value.replace(" ","T"));if(Number.isNaN(date.getTime()))return"";return date.toLocaleString("en-KE",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"})}
function longDate(value:string|null){if(!value)return"Open-ended";const date=new Date(value);if(Number.isNaN(date.getTime()))return"—";return date.toLocaleDateString("en-KE",{day:"numeric",month:"short",year:"numeric"})}

function TenantLeasePage(){
 const[loading,setLoading]=useState(true);const[agreement,setAgreement]=useState<Agreement|null>(null);const[error,setError]=useState("");const[tenantTerms,setTenantTerms]=useState("");const[requestedStart,setRequestedStart]=useState("");const[requestedEnd,setRequestedEnd]=useState("");const[savingTerms,setSavingTerms]=useState(false);const[termsMessage,setTermsMessage]=useState("");const[initials,setInitials]=useState("");const[signing,setSigning]=useState(false);const[markingPaid,setMarkingPaid]=useState(false);const[depositMessage,setDepositMessage]=useState("");const[savingEndDate,setSavingEndDate]=useState(false);const[endDateMessage,setEndDateMessage]=useState("");const[downloading,setDownloading]=useState(false);
 const load=useCallback(async()=>{try{const response=await apiRequest("/tenant/lease-agreement");const parsed=asAgreement(response);setAgreement(parsed);setTenantTerms(parsed?.tenant_terms??"");setRequestedStart(parsed?.requested_move_in_date??"");setRequestedEnd(parsed?.requested_move_out_date??"");setError("")}catch(caught){setError(caught instanceof Error?caught.message:"We couldn't load your lease agreement.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const tenantSigned=Boolean(agreement?.tenant_signed_at);const managerSigned=Boolean(agreement?.manager_signed_at);const leaseLocked=managerSigned;const termsChanged=useMemo(()=>((agreement?.tenant_terms??"")!==tenantTerms||(agreement?.requested_move_in_date??"")!==requestedStart||(agreement?.requested_move_out_date??"")!==requestedEnd),[agreement?.tenant_terms,agreement?.requested_move_in_date,agreement?.requested_move_out_date,tenantTerms,requestedStart,requestedEnd]);
 async function handleSaveTerms(e:FormEvent){e.preventDefault();if(!agreement)return;setSavingTerms(true);setTermsMessage("");try{const response=await apiRequest("/tenant/lease-agreement",{method:"PATCH",body:JSON.stringify({tenant_terms:tenantTerms,requested_move_in_date:requestedStart||null,requested_move_out_date:requestedEnd||null})});const parsed=asAgreement(response);if(parsed){setAgreement(parsed);setTenantTerms(parsed.tenant_terms??"");setRequestedStart(parsed.requested_move_in_date??"");setRequestedEnd(parsed.requested_move_out_date??"")}setTermsMessage("Your copy has been saved.")}catch(caught){setTermsMessage(caught instanceof Error?caught.message:"Couldn't save your changes.")}finally{setSavingTerms(false)}}
 async function handleSign(){if(!initials.trim()||!agreement||leaseLocked||tenantSigned)return;setSigning(true);setTermsMessage("");try{const response=await apiRequest("/tenant/lease-agreement",{method:"PATCH",body:JSON.stringify({tenant_signature:initials.trim()})});const parsed=asAgreement(response);if(parsed){setAgreement(parsed);setTenantTerms(parsed.tenant_terms??"");setRequestedStart(parsed.requested_move_in_date??"");setRequestedEnd(parsed.requested_move_out_date??"")}setInitials("");setTermsMessage("Signed — your copy of the agreement is now locked in.")}catch(caught){setTermsMessage(caught instanceof Error?caught.message:"Couldn't record your signature.")}finally{setSigning(false)}}
 async function handleMarkDepositPaid(){setMarkingPaid(true);setDepositMessage("");try{const response=await apiRequest("/tenant/deposit/mark-paid",{method:"POST"});const parsed=asAgreement(response);if(parsed)setAgreement(parsed);setDepositMessage("Thanks — we've let your property manager know to confirm receipt.")}catch(caught){setDepositMessage(caught instanceof Error?caught.message:"Couldn't record this.")}finally{setMarkingPaid(false)}}
 const deposit=agreement?.deposit;const depositConfirmed=deposit?.status==="paid";const depositRequired=Number(deposit?.amount_required??0)>0;const depositTenantMarked=Boolean(deposit?.tenant_marked_paid_at);const downloadReady=managerSigned&&tenantSigned&&(!depositRequired||depositConfirmed);useEffect(()=>{if(!tenantSigned||downloadReady)return;const interval=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(interval)},[tenantSigned,downloadReady,load]);
 async function handleSaveEndDate(){if(!agreement||!managerSigned)return;setSavingEndDate(true);setEndDateMessage("");try{const response=await apiRequest("/tenant/lease-agreement/end-date",{method:"PATCH",body:JSON.stringify({end_date:requestedEnd||null})});const parsed=asAgreement(response);if(parsed){setAgreement(parsed);setRequestedEnd(parsed.end_date??"")}setEndDateMessage("Lease end date updated.")}catch(caught){setEndDateMessage(caught instanceof Error?caught.message:"Couldn't update the lease end date.")}finally{setSavingEndDate(false)}}
 async function handleDownload(){if(!downloadReady)return;setDownloading(true);setEndDateMessage("");try{await downloadFile("/tenant/lease-agreement/download","signed-lease-agreement.html")}catch(caught){setEndDateMessage(caught instanceof Error?caught.message:"Couldn't download the signed lease.")}finally{setDownloading(false)}}
 return <TenantDashboardLayout title="Lease agreement" subtitle="Review your agreement, confirm your details and sign securely." pageClassName="tl-page"><style>{styles}</style><div className="tl-stack">{error&&<p className="tp-card" role="status">{error}</p>}{loading?<span className="tp-skeleton tl-skeleton"/>:!agreement?<div className="tp-card tl-empty"><span className="tl-empty__icon"><FileText/></span><h3 className="tp-empty__title">No lease agreement yet</h3><p className="tp-empty__text">Once your property manager assigns you to a unit, a digital lease agreement will appear here for you to review and sign.</p></div>:<>
 <section className="tp-card tl-hero" aria-label="Lease header"><div className="tl-hero__content"><div><p className="tl-eyebrow">Official tenancy document</p><h2>{agreement.property?.name??"Property"}</h2><p className="tl-hero__sub">Unit {agreement.unit?.unit_number??"—"}{agreement.unit?.unit_type?` · ${agreement.unit.unit_type}`:""} · {agreement.property?.city??agreement.property?.address??""}</p></div><div className="tl-hero__badges"><span className="tl-badge tl-badge--gold"><FileSignature/>Digital lease</span><span className="tl-badge tl-badge--dark">{leaseLocked?<ShieldCheck/>:<Clock/>}{leaseLocked?"Lease locked":"Awaiting signatures"}</span></div></div></section>
 <section className="tp-card tl-overview" aria-label="Lease overview"><div className="tl-section-head"><div><h3>Lease overview</h3><p>Key parties, dates and financial terms at a glance.</p></div><span className="tl-section-label"><ShieldCheck/>Verified record</span></div><div className="tl-parties"><div className="tl-party"><span className="tl-label">Organization</span><span className="tl-value">{agreement.organization?.name??"—"}</span></div><div className="tl-party"><span className="tl-label">Property / unit</span><span className="tl-value">{agreement.property?.name??"—"} · {agreement.unit?.unit_number??"—"}</span></div></div><div className="tl-timeline">
  <div className="tl-date"><span className="tl-date__dot"/><span className="tl-label">Official start</span><span className="tl-date__value">{agreement.start_date?longDate(agreement.start_date):"Not confirmed"}</span><span className="tl-date__hint">Confirmed lease commencement</span></div>
  <div className="tl-date"><span className="tl-date__dot"/><span className="tl-label">Requested start</span><span className="tl-date__value">{longDate(agreement.requested_move_in_date)}</span><span className="tl-date__hint">Your requested move-in date</span></div>
  <div className="tl-date tl-date--official"><span className="tl-date__dot"/><span className="tl-label">Official end</span>{leaseLocked?<><div className="tl-end-editor"><input aria-label="Lease end date" type="date" value={agreement.end_date??""} onChange={e=>setRequestedEnd(e.target.value)}/><button className="tl-icon-save" type="button" aria-label="Save lease end date" title="Save lease end date" disabled={savingEndDate} onClick={handleSaveEndDate}>{savingEndDate?<Loader2 className="tl-spin"/>:<CheckCircle2/>}</button></div>{endDateMessage&&<p className="tl-message" role="status">{endDateMessage}</p>}</>:<><span className="tl-date__value">{longDate(agreement.end_date)}</span><span className="tl-date__hint">Final lease end date</span></>}</div>
  <div className="tl-date"><span className="tl-date__dot"/><span className="tl-label">Requested end</span><span className="tl-date__value">{longDate(agreement.requested_move_out_date)}</span><span className="tl-date__hint">Your requested move-out date</span></div></div><div className="tl-financials"><div className="tl-financial"><span className="tl-label">Monthly rent</span><strong>KSh {Number(agreement.monthly_rent??0).toLocaleString()}</strong></div><div className="tl-financial"><span className="tl-label">Rent due</span><strong>{agreement.rent_due_day}th of each month</strong></div></div><div className="tl-info"><Info/><p>Property, unit, rent, official dates and deposit terms are controlled by the organization's lease record. Your requested dates and agreement copy can be edited before you sign. Once signed, the document becomes read-only. After the manager signs, only the official lease end date remains editable here.</p></div></section>
 {deposit&&<section className="tp-card tl-deposit" aria-label="Deposit status"><div className="tl-deposit__main"><span className="tl-label">Security deposit</span><p className="tl-deposit__amount">{!depositRequired?"No security deposit is required for this lease.":`KSh ${Number(deposit.amount_required??agreement.deposit_amount??0).toLocaleString()} required · KSh ${Number(deposit.amount_paid??0).toLocaleString()} received`}</p>{depositRequired&&<p className="tl-deposit__status">{depositConfirmed?"Confirmed as received by your property manager.":depositTenantMarked?"You've marked this as paid — waiting for manager confirmation.":"Not yet confirmed as paid."}</p>}{depositMessage&&<p className="tl-message" role="status">{depositMessage}</p>}</div>{depositRequired&&!depositConfirmed&&!depositTenantMarked&&<button className="tl-deposit__action" type="button" disabled={markingPaid} onClick={handleMarkDepositPaid}>{markingPaid?<Loader2 className="tl-spin"/>:<CheckCircle2/>}I've paid my deposit</button>}{depositConfirmed&&<span className="tl-badge tl-badge--done"><BadgeCheck/>Confirmed</span>}</section>}
 {tenantSigned&&!managerSigned&&<section className="tl-status" aria-label="Manager confirmation status"><div className="tl-status__icon"><Clock/></div><div><strong>Your signature is locked.</strong><p>The property manager still needs to review and sign the final agreement. This page will update automatically.</p></div></section>}{managerSigned&&!downloadReady&&<section className="tl-status" aria-label="Final lease status"><div className="tl-status__icon"><ShieldCheck/></div><div><strong>Manager signature recorded.</strong><p>Your signed agreement is locked. The download will appear once the deposit is confirmed.</p></div></section>}{downloadReady&&<section className="tp-card tl-complete" aria-label="Completed signed lease"><div className="tl-complete__top"><div><h3>Signed lease complete</h3><p>Both parties have signed and the deposit has been confirmed. Keep an offline copy of the completed agreement.</p></div><span className="tl-badge tl-badge--done"><BadgeCheck/>Complete</span></div><button className="tl-download" type="button" disabled={downloading} onClick={handleDownload}><span>{downloading?<Loader2 className="tl-spin"/>:<FileText/>} Download signed lease copy</span><ArrowRight/></button></section>}
 <div className="tl-docs"><article className="tp-card tl-doc"><div className="tl-doc__head"><div className="tl-doc__title"><span className="tl-doc__title-icon"><FileText/></span><div><h3>Manager's copy</h3><p className="tl-doc__sub">Reference copy · read-only</p></div></div><span className={`tl-badge ${managerSigned?"tl-badge--done":"tl-badge--pending"}`}>{managerSigned?<CheckCircle2/>:<Clock/>}{managerSigned?"Signed":"Not signed"}</span></div><textarea value={agreement.manager_terms??""} disabled readOnly aria-label="Manager's copy of the lease agreement"/>{managerSigned&&<div className="tl-signed"><span className="tl-signed__initials">{agreement.manager_signature}</span><div className="tl-signed__meta"><span className="tl-signed__stamp">SIGNED BY MANAGER</span><span className="tl-signed__date">{longDateTime(agreement.manager_signed_at)}</span></div></div>}<p className="tl-doc__hint">This is the property manager's version of the agreement. It is displayed for comparison and reference.</p></article>
 <article className="tp-card tl-doc"><form onSubmit={handleSaveTerms}><div className="tl-doc__head"><div className="tl-doc__title"><span className="tl-doc__title-icon"><FileSignature/></span><div><h3>Your copy</h3><p className="tl-doc__sub">Review, edit and sign</p></div></div><span className={`tl-badge ${tenantSigned?"tl-badge--done":"tl-badge--pending"}`}>{tenantSigned?<CheckCircle2/>:<Clock/>}{tenantSigned?"Signed":"Action required"}</span></div>{!tenantSigned&&<div className="tl-date-card"><p className="tl-date-card__title">Your requested tenancy dates</p><p className="tl-date-card__hint">These are your requested dates. The official lease dates above remain the authoritative dates in the agreement.</p><div className="tl-date-fields"><div className="tl-date-field"><label htmlFor="requested-start">Requested start</label><input id="requested-start" type="date" value={requestedStart} onChange={e=>setRequestedStart(e.target.value)} disabled={leaseLocked}/></div><div className="tl-date-field"><label htmlFor="requested-end">Requested end</label><input id="requested-end" type="date" value={requestedEnd} onChange={e=>setRequestedEnd(e.target.value)} disabled={leaseLocked}/></div></div></div>}<textarea value={tenantTerms} onChange={e=>setTenantTerms(e.target.value)} disabled={tenantSigned||leaseLocked} aria-label="Your copy of the lease agreement"/>{tenantSigned&&<div className="tl-signed"><span className="tl-signed__initials">{agreement.tenant_signature}</span><div className="tl-signed__meta"><span className="tl-signed__stamp">SIGNED BY TENANT</span><span className="tl-signed__date">{longDateTime(agreement.tenant_signed_at)}</span></div></div>}<p className="tl-doc__hint">{tenantSigned?"You have signed this version. It is now with the manager for final review.":"Review your copy carefully. Save any changes before entering your signature."}</p><div className="tl-actions"><button className="tl-save" type="submit" disabled={savingTerms||!termsChanged||tenantSigned||leaseLocked}>{savingTerms?<Loader2 className="tl-spin"/>:null}Save changes</button>{!tenantSigned&&<div className="tl-sign"><label htmlFor="tenant-initials">Sign with initials</label><input id="tenant-initials" value={initials} onChange={e=>setInitials(e.target.value)} maxLength={6} placeholder="e.g. JM"/><button type="button" disabled={signing||!initials.trim()} onClick={()=>void handleSign()}>{signing?<Loader2 className="tl-spin"/>:<FileSignature/>}Sign</button></div>}</div>{termsMessage&&<p className="tl-feedback" role="status">{termsMessage}</p>}{endDateMessage&&<p className="tl-feedback" role="status">{endDateMessage}</p>}</form></article></div>
 </>}</div></TenantDashboardLayout>;
}

export default TenantLeasePage;
