import { useCallback, useEffect, useRef, useState } from "react";
import { Camera, IdCard, KeyRound, MapPin, ShieldCheck, UserRound } from "lucide-react";
import TenantDashboardLayout from "../../layouts/TenantDashboardLayout";
import { apiRequest } from "../../services/api";

interface TenantProfile {
  id: number; first_name: string; last_name: string; name: string;
  email: string | null; phone: string | null; username: string | null;
  national_id: string | null; residential_address: string | null;
  postal_address: string | null; nationality: string | null;
  employer_name: string | null; employer_phone: string | null;
  next_of_kin_name: string | null; next_of_kin_phone: string | null;
  profile_photo_url: string | null;
}
function parseProfile(payload: unknown): TenantProfile | null {
  if (!payload || typeof payload !== "object") return null;
  const record = payload as Record<string, unknown>;
  const source = record.data && typeof record.data === "object" ? record.data as Record<string, unknown> : record;
  return source.id ? source as unknown as TenantProfile : null;
}
function initials(name: string) {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  return parts.length > 1 ? `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase() : (parts[0]?.slice(0, 2) || "T").toUpperCase();
}
const styles = `
.tp-profile{display:flex;flex-direction:column;gap:1rem;max-width:58rem;margin:0 auto}
.tp-profile-hero{display:grid;grid-template-columns:auto 1fr;gap:1.25rem;align-items:center;padding:1.5rem;border:1px solid var(--tp-line);border-radius:1.25rem;background:linear-gradient(135deg,#fff,#f8fafc);box-shadow:var(--tp-shadow-sm)}
.tp-profile-avatar{position:relative;width:6.5rem;height:6.5rem;border-radius:50%;overflow:hidden;display:flex;align-items:center;justify-content:center;background:var(--tp-blue-pale);color:var(--tp-blue-dark);font-size:1.5rem;font-weight:750;border:4px solid #fff;box-shadow:0 5px 20px rgba(15,23,42,.1)}
.tp-profile-avatar img{width:100%;height:100%;object-fit:cover}.tp-profile-avatar__button{position:absolute;right:0;bottom:0;width:2.1rem;height:2.1rem;border-radius:50%;display:flex;align-items:center;justify-content:center;background:var(--tp-blue);color:#fff;border:3px solid #fff;cursor:pointer}.tp-profile-avatar__button svg{width:.9rem;height:.9rem}
.tp-profile-hero h2{margin:0;font-size:1.35rem;letter-spacing:-.025em}.tp-profile-hero p{margin:.35rem 0 0;color:var(--tp-muted);font-size:.8rem}
.tp-profile-account{display:flex;flex-wrap:wrap;gap:.45rem;margin-top:.7rem}.tp-profile-chip{display:inline-flex;align-items:center;gap:.35rem;padding:.35rem .6rem;border:1px solid var(--tp-line);border-radius:999px;background:#fff;color:var(--tp-ink-soft);font-size:.68rem;font-weight:650}.tp-profile-chip svg{width:.8rem;height:.8rem;color:var(--tp-blue)}
.tp-profile-card{padding:1.25rem;border:1px solid var(--tp-line);border-radius:1rem;background:#fff;box-shadow:var(--tp-shadow-sm)}.tp-profile-card__head{display:flex;align-items:flex-start;gap:.7rem;margin-bottom:1rem}.tp-profile-card__icon{width:2.25rem;height:2.25rem;display:flex;align-items:center;justify-content:center;border-radius:.7rem;background:var(--tp-surface-tint);color:var(--tp-blue);flex:none}.tp-profile-card__icon svg{width:1.05rem;height:1.05rem}.tp-profile-card h3{margin:0;font-size:.95rem;font-weight:700}.tp-profile-card__head p{margin:.2rem 0 0;color:var(--tp-muted);font-size:.72rem;line-height:1.5}
.tp-profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.85rem 1rem}.tp-profile-field{display:flex;flex-direction:column;gap:.32rem}.tp-profile-field--full{grid-column:1/-1}.tp-profile-field label{font-size:.67rem;font-weight:700;color:#64748b}.tp-profile-field input,.tp-profile-field textarea{width:100%;box-sizing:border-box;padding:.68rem .75rem;border:1px solid var(--tp-line);border-radius:.65rem;background:#fff;outline:none;resize:vertical}.tp-profile-field input:focus,.tp-profile-field textarea:focus{border-color:#93b4df;box-shadow:0 0 0 3px rgba(37,99,235,.08)}.tp-profile-field input[readonly]{background:var(--tp-surface-sunken);color:var(--tp-muted)}
.tp-profile-actions{display:flex;justify-content:flex-end;margin-top:1rem}.tp-profile-save{min-height:2.5rem;padding:0 1rem;border-radius:.65rem;background:var(--tp-blue);color:#fff;font-weight:700}.tp-profile-message{padding:.7rem .85rem;border-radius:.65rem;background:var(--tp-green-pale);color:var(--tp-green);font-size:.75rem}.tp-profile-error{padding:.7rem .85rem;border-radius:.65rem;background:var(--tp-red-pale);color:var(--tp-red);font-size:.75rem}.tp-profile-note{margin:0;color:var(--tp-muted);font-size:.7rem;line-height:1.55}
@media(max-width:620px){.tp-profile-hero{grid-template-columns:1fr;text-align:center;justify-items:center}.tp-profile-account{justify-content:center}.tp-profile-grid{grid-template-columns:1fr}.tp-profile-field--full{grid-column:auto}.tp-profile-actions{justify-content:stretch}.tp-profile-save{width:100%}}
`;
function TenantProfilePage(){
  const [profile,setProfile]=useState<TenantProfile|null>(null);
  const [phone,setPhone]=useState(""); const [nationalId,setNationalId]=useState("");
  const [residentialAddress,setResidentialAddress]=useState(""); const [postalAddress,setPostalAddress]=useState("");
  const [nationality,setNationality]=useState(""); const [employer,setEmployer]=useState(""); const [employerPhone,setEmployerPhone]=useState("");
  const [nextOfKin,setNextOfKin]=useState(""); const [nextOfKinPhone,setNextOfKinPhone]=useState("");
  const [saving,setSaving]=useState(false); const [photoBusy,setPhotoBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const fileRef=useRef<HTMLInputElement>(null);
  const apply=(p:TenantProfile)=>{setProfile(p);setPhone(p.phone??"");setNationalId(p.national_id??"");setResidentialAddress(p.residential_address??"");setPostalAddress(p.postal_address??"");setNationality(p.nationality??"");setEmployer(p.employer_name??"");setEmployerPhone(p.employer_phone??"");setNextOfKin(p.next_of_kin_name??"");setNextOfKinPhone(p.next_of_kin_phone??"");};
  const load=useCallback(async()=>{try{const p=parseProfile(await apiRequest("/tenant/profile"));if(!p)throw new Error("We couldn't load your profile.");apply(p);}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't load your profile.");}},[]);
  useEffect(()=>{void load();},[load]);
  async function save(){setSaving(true);setMessage("");setError("");try{const p=parseProfile(await apiRequest("/tenant/profile",{method:"PATCH",body:JSON.stringify({phone:phone.trim(),national_id:nationalId.trim()||null,residential_address:residentialAddress.trim()||null,postal_address:postalAddress.trim()||null,nationality:nationality.trim()||null,employer_name:employer.trim()||null,employer_phone:employerPhone.trim()||null,next_of_kin_name:nextOfKin.trim()||null,next_of_kin_phone:nextOfKinPhone.trim()||null})}));if(p)apply(p);setMessage("Your profile is up to date. These details will be used in your lease agreement.");}catch(cause){setError(cause instanceof Error?cause.message:"Couldn't save your profile.");}finally{setSaving(false);}}
  async function uploadPhoto(file:File){setPhotoBusy(true);setMessage("");setError("");try{const form=new FormData();form.append("profile_photo",file);const p=parseProfile(await apiRequest("/tenant/profile/photo",{method:"POST",body:form}));if(p)apply(p);setMessage("Profile picture updated.");}catch(cause){setError(cause instanceof Error?cause.message:"Couldn't upload that picture.");}finally{setPhotoBusy(false);}}
  async function removePhoto(){setPhotoBusy(true);setMessage("");setError("");try{const p=parseProfile(await apiRequest("/tenant/profile/photo",{method:"DELETE"}));if(p)apply(p);setMessage("Profile picture removed.");}catch(cause){setError(cause instanceof Error?cause.message:"Couldn't remove your picture.");}finally{setPhotoBusy(false);}}
  return <TenantDashboardLayout title="My profile" subtitle="Keep the details used for your account and lease agreement accurate." pageClassName="tp-profile-page"><style>{styles}</style><div className="tp-profile">
    {message&&<div className="tp-profile-message" role="status">{message}</div>}{error&&<div className="tp-profile-error" role="alert">{error}</div>}
    <section className="tp-profile-hero"><div className="tp-profile-avatar">{profile?.profile_photo_url?<img src={profile.profile_photo_url} alt={profile.name}/>:initials(profile?.name??"Tenant")}<button type="button" className="tp-profile-avatar__button" onClick={()=>fileRef.current?.click()} disabled={photoBusy} aria-label="Upload profile picture"><Camera/></button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadPhoto(file);e.currentTarget.value="";}}/></div><div><h2>{profile?.name??"Your profile"}</h2><p>Optional profile picture. Your username is generated by the system and is used to sign in.</p><div className="tp-profile-account"><span className="tp-profile-chip"><KeyRound/> @{profile?.username??"username"}</span><span className="tp-profile-chip"><ShieldCheck/> Tenant account</span>{profile?.email&&<span className="tp-profile-chip">{profile.email}</span>}</div>{profile?.profile_photo_url&&<button type="button" className="tp-btn tp-btn--link" style={{marginTop:".7rem"}} onClick={()=>void removePhoto()} disabled={photoBusy}>Remove picture</button>}</div></section>
    <section className="tp-profile-card"><div className="tp-profile-card__head"><span className="tp-profile-card__icon"><UserRound/></span><div><h3>Personal & contact details</h3><p>Your name and account email are tied to your account. Keep your contact and identity details current.</p></div></div><div className="tp-profile-grid">
      <div className="tp-profile-field"><label>First name</label><input value={profile?.first_name??""} readOnly/></div><div className="tp-profile-field"><label>Last name</label><input value={profile?.last_name??""} readOnly/></div><div className="tp-profile-field"><label>Email</label><input value={profile?.email??""} readOnly/></div><div className="tp-profile-field"><label>Phone *</label><input value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="tp-profile-field"><label>National ID</label><input value={nationalId} onChange={e=>setNationalId(e.target.value)} placeholder="Not provided"/></div><div className="tp-profile-field"><label>Nationality</label><input value={nationality} onChange={e=>setNationality(e.target.value)} placeholder="Not provided"/></div><div className="tp-profile-field tp-profile-field--full"><label>Residential address</label><textarea rows={2} value={residentialAddress} onChange={e=>setResidentialAddress(e.target.value)} placeholder="Your current residential address"/></div><div className="tp-profile-field tp-profile-field--full"><label>Postal address</label><input value={postalAddress} onChange={e=>setPostalAddress(e.target.value)} placeholder="Optional postal address"/></div>
    </div></section>
    <section className="tp-profile-card"><div className="tp-profile-card__head"><span className="tp-profile-card__icon"><IdCard/></span><div><h3>Employment & next of kin</h3><p>These details are available for tenancy records and contracts. Optional fields can remain “Not provided”.</p></div></div><div className="tp-profile-grid"><div className="tp-profile-field"><label>Employer</label><input value={employer} onChange={e=>setEmployer(e.target.value)} placeholder="Not provided"/></div><div className="tp-profile-field"><label>Employer phone</label><input value={employerPhone} onChange={e=>setEmployerPhone(e.target.value)} placeholder="Not provided"/></div><div className="tp-profile-field"><label>Next of kin</label><input value={nextOfKin} onChange={e=>setNextOfKin(e.target.value)} placeholder="Not provided"/></div><div className="tp-profile-field"><label>Next of kin phone</label><input value={nextOfKinPhone} onChange={e=>setNextOfKinPhone(e.target.value)} placeholder="Not provided"/></div></div><div className="tp-profile-actions"><button type="button" className="tp-profile-save" onClick={()=>void save()} disabled={saving||!phone.trim()}>{saving?"Saving…":"Save profile"}</button></div></section>
    <section className="tp-profile-card"><div className="tp-profile-card__head"><span className="tp-profile-card__icon"><MapPin/></span><div><h3>Lease information</h3><p>Property, unit, rent and lease dates are managed from your tenancy and agreement records.</p></div></div><p className="tp-profile-note">Before signing, changes to your profile are reflected in your unsigned lease agreement. Once signed, contractual records are protected from profile edits.</p></section>
  </div></TenantDashboardLayout>;
}
export default TenantProfilePage;
